# Boolean Indexing

In [1]:
import numpy as np

In [16]:
# names
names = np.array(['Max', 'Jon', 'Lil', 'Park', 'Max', 'Mark'])

In [64]:
data = np.random.randn(6, 4)
data

array([[ 0.14532149,  1.40522785, -1.23560226, -0.44874523],
       [ 0.60497074, -0.61940993, -0.16413718,  0.95986636],
       [ 0.4199986 , -1.4380679 ,  0.88936608,  1.72519475],
       [-0.50458881,  0.29317082,  0.90363109,  0.62828452],
       [-0.83676919, -0.72619652, -1.58175138, -0.91908758],
       [ 1.6826376 , -0.37931113,  0.37271843,  0.10282926]])

In [54]:
# Bir isimga tegishli ma'lumotni chiqarish.

data[names == 'Max']   #'Max'ga tegishli ma'/tni chiqarsin

array([[-0.09036496, -1.08829764, -1.02743119, -0.39707246],
       [-0.6368737 ,  1.9062084 ,  2.31559788, -0.31080987]])

In [55]:
data[names == 'Park', 3] # Parkga tegishli ma'/tni 3indeksdagisini chiqarsin

array([-1.68599829])

In [56]:
data[names == 'Mark', 2: ] #tegishili ma'/tni 2da keyingi xammasini chiqarsin

array([[ 2.13699215, -0.27486966]])

In [57]:
# agar teng bo'lmasa 

data[names != 'Max'] # (!=) Maxga tegishli bo'lmagan ma'/tlarni chiqarsin

array([[-0.24397417, -0.86046826,  0.65365226,  2.2414908 ],
       [-1.11882012,  0.10213092,  2.05561798, -1.22385173],
       [ 0.71241819,  0.03210813,  0.46168371, -1.68599829],
       [ 1.7589255 , -1.16044096,  2.13699215, -0.27486966]])

In [58]:
# yoki
data[~(names == 'Max')] # (~) ham (!=) cell kabi bir xil natija beradi

array([[-0.24397417, -0.86046826,  0.65365226,  2.2414908 ],
       [-1.11882012,  0.10213092,  2.05561798, -1.22385173],
       [ 0.71241819,  0.03210813,  0.46168371, -1.68599829],
       [ 1.7589255 , -1.16044096,  2.13699215, -0.27486966]])

In [59]:
# 2 ta ismga tegishli ma'lumotni chiqarish

mask = (names == 'Jon') | (names == 'Lil') 
data[mask] 

array([[-0.24397417, -0.86046826,  0.65365226,  2.2414908 ],
       [-1.11882012,  0.10213092,  2.05561798, -1.22385173]])

In [65]:
data

array([[ 0.14532149,  1.40522785, -1.23560226, -0.44874523],
       [ 0.60497074, -0.61940993, -0.16413718,  0.95986636],
       [ 0.4199986 , -1.4380679 ,  0.88936608,  1.72519475],
       [-0.50458881,  0.29317082,  0.90363109,  0.62828452],
       [-0.83676919, -0.72619652, -1.58175138, -0.91908758],
       [ 1.6826376 , -0.37931113,  0.37271843,  0.10282926]])

In [67]:
data[data < 0] = 0 # 0dan kichik barcha ma'/tlarni 0ga tenglashtirsin
data

array([[0.14532149, 1.40522785, 0.        , 0.        ],
       [0.60497074, 0.        , 0.        , 0.95986636],
       [0.4199986 , 0.        , 0.88936608, 1.72519475],
       [0.        , 0.29317082, 0.90363109, 0.62828452],
       [0.        , 0.        , 0.        , 0.        ],
       [1.6826376 , 0.        , 0.37271843, 0.10282926]])

# Amaliy mashq

In [111]:
# 0dan 9 gacha bo'lgan 1qadamli shape(3,3)li massiv yaratish
def nd_arange():
    a = np.arange(9).reshape(3,3)
    return a
nd_arange()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
# yuqoridagi massivni array[6,7] ni chiqarish
def sliced_arr():
    a = np.arange(9).reshape(3,3)
    sl_arr = a[2, 0:2]
    return sl_arr
sliced_arr()

array([6, 7])

In [113]:
# 3d arraydan array[12,13][15,16] ni chiqarish
def sl_arr_3d():
    arr3d = np.array([[[ 0,  1,  2],
                       [ 3,  4,  5],
                       [ 6,  7,  8]],

                      [[ 9, 10, 11],
                       [12, 13, 14],
                       [15, 16, 17]],

                      [[18, 19, 20],
                       [21, 22, 23],
                       [24, 25, 26]]])
    sl_arr = arr3d[1]
    return sl_arr[1:3, 0:2]
sl_arr_3d()

array([[12, 13],
       [15, 16]])

In [117]:
#islmlarga tegishli ma'lumotlar!
def boolean_sl():
    names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    data =  np.array([[2,4,5,6],
                      [4,6,8,5],
                      [7,6,8,5],
                      [1,3,4,5],
                      [8,5,3,1],
                      [7,3,7,5],
                      [5,7,5,1]])
    mask = (names == 'Javohir') | (names == 'Elyor')
    return data[mask]
boolean_sl()

array([[7, 6, 8, 5],
       [1, 3, 4, 5],
       [7, 3, 7, 5],
       [5, 7, 5, 1]])